/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tamarix.compliance.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.tamarix.compliance.model.Compliance;
import com.tamarix.compliance.model.ComplianceModel;
import com.tamarix.compliance.model.ComplianceSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Compliance service. Represents a row in the &quot;Compliance_Compliance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ComplianceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ComplianceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ComplianceImpl
 * @generated
 */
@JSON(strict = true)
public class ComplianceModelImpl
	extends BaseModelImpl<Compliance> implements ComplianceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a compliance model instance should use the <code>Compliance</code> interface instead.
	 */
	public static final String TABLE_NAME = "Compliance_Compliance";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"complianceId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdby", Types.BIGINT}, {"modifiedby", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"firstName", Types.VARCHAR}, {"lastName", Types.VARCHAR},
		{"branchName", Types.VARCHAR}, {"payrollNo", Types.VARCHAR},
		{"terminationReason", Types.VARCHAR},
		{"terminationCode", Types.VARCHAR}, {"formerBranch", Types.VARCHAR},
		{"contractId", Types.VARCHAR}, {"entityId", Types.VARCHAR},
		{"approvalDate", Types.VARCHAR}, {"comments", Types.VARCHAR},
		{"approverContractNumber", Types.VARCHAR},
		{"agentVerdict", Types.VARCHAR}, {"agentAction", Types.VARCHAR},
		{"processedFlag", Types.VARCHAR}, {"errorReason", Types.VARCHAR},
		{"assignmentStatus", Types.VARCHAR}, {"capacity", Types.VARCHAR},
		{"positionId", Types.VARCHAR}, {"orgId", Types.VARCHAR},
		{"historyStartDate", Types.VARCHAR}, {"oldOrgId", Types.VARCHAR},
		{"oldPositionId", Types.VARCHAR},
		{"contractEffectiveEndDate", Types.VARCHAR},
		{"applicationTye", Types.VARCHAR},
		{"applicationCategory", Types.VARCHAR},
		{"firstapprover", Types.VARCHAR}, {"secondapprover", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("complianceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdby", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedby", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("branchName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("payrollNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("terminationReason", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("terminationCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("formerBranch", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contractId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entityId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("approvalDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("comments", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("approverContractNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agentVerdict", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agentAction", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("processedFlag", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("errorReason", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assignmentStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("capacity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("positionId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("orgId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("historyStartDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oldOrgId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oldPositionId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contractEffectiveEndDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("applicationTye", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("applicationCategory", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("firstapprover", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondapprover", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Compliance_Compliance (uuid_ VARCHAR(75) null,complianceId LONG not null primary key,groupId LONG,companyId LONG,createdby LONG,modifiedby VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,firstName VARCHAR(75) null,lastName VARCHAR(75) null,branchName VARCHAR(75) null,payrollNo VARCHAR(75) null,terminationReason VARCHAR(75) null,terminationCode VARCHAR(75) null,formerBranch VARCHAR(75) null,contractId VARCHAR(75) null,entityId VARCHAR(75) null,approvalDate VARCHAR(75) null,comments VARCHAR(75) null,approverContractNumber VARCHAR(75) null,agentVerdict VARCHAR(75) null,agentAction VARCHAR(75) null,processedFlag VARCHAR(75) null,errorReason VARCHAR(75) null,assignmentStatus VARCHAR(75) null,capacity VARCHAR(75) null,positionId VARCHAR(75) null,orgId VARCHAR(75) null,historyStartDate VARCHAR(75) null,oldOrgId VARCHAR(75) null,oldPositionId VARCHAR(75) null,contractEffectiveEndDate VARCHAR(75) null,applicationTye VARCHAR(75) null,applicationCategory VARCHAR(75) null,firstapprover VARCHAR(75) null,secondapprover VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Compliance_Compliance";

	public static final String ORDER_BY_JPQL =
		" ORDER BY compliance.complianceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Compliance_Compliance.complianceId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.tamarix.compliance.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.tamarix.compliance.model.Compliance"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.tamarix.compliance.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.tamarix.compliance.model.Compliance"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.tamarix.compliance.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.tamarix.compliance.model.Compliance"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long COMPLIANCEID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Compliance toModel(ComplianceSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Compliance model = new ComplianceImpl();

		model.setUuid(soapModel.getUuid());
		model.setComplianceId(soapModel.getComplianceId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreatedby(soapModel.getCreatedby());
		model.setModifiedby(soapModel.getModifiedby());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setFirstName(soapModel.getFirstName());
		model.setLastName(soapModel.getLastName());
		model.setBranchName(soapModel.getBranchName());
		model.setPayrollNo(soapModel.getPayrollNo());
		model.setTerminationReason(soapModel.getTerminationReason());
		model.setTerminationCode(soapModel.getTerminationCode());
		model.setFormerBranch(soapModel.getFormerBranch());
		model.setContractId(soapModel.getContractId());
		model.setEntityId(soapModel.getEntityId());
		model.setApprovalDate(soapModel.getApprovalDate());
		model.setComments(soapModel.getComments());
		model.setApproverContractNumber(soapModel.getApproverContractNumber());
		model.setAgentVerdict(soapModel.getAgentVerdict());
		model.setAgentAction(soapModel.getAgentAction());
		model.setProcessedFlag(soapModel.getProcessedFlag());
		model.setErrorReason(soapModel.getErrorReason());
		model.setAssignmentStatus(soapModel.getAssignmentStatus());
		model.setCapacity(soapModel.getCapacity());
		model.setPositionId(soapModel.getPositionId());
		model.setOrgId(soapModel.getOrgId());
		model.setHistoryStartDate(soapModel.getHistoryStartDate());
		model.setOldOrgId(soapModel.getOldOrgId());
		model.setOldPositionId(soapModel.getOldPositionId());
		model.setContractEffectiveEndDate(
			soapModel.getContractEffectiveEndDate());
		model.setApplicationTye(soapModel.getApplicationTye());
		model.setApplicationCategory(soapModel.getApplicationCategory());
		model.setFirstapprover(soapModel.getFirstapprover());
		model.setSecondapprover(soapModel.getSecondapprover());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Compliance> toModels(ComplianceSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Compliance> models = new ArrayList<Compliance>(soapModels.length);

		for (ComplianceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.tamarix.compliance.service.util.ServiceProps.get(
			"lock.expiration.time.com.tamarix.compliance.model.Compliance"));

	public ComplianceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _complianceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setComplianceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _complianceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Compliance.class;
	}

	@Override
	public String getModelClassName() {
		return Compliance.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Compliance, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Compliance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Compliance, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Compliance)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Compliance, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Compliance, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Compliance)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Compliance, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Compliance, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Compliance>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Compliance.class.getClassLoader(), Compliance.class,
			ModelWrapper.class);

		try {
			Constructor<Compliance> constructor =
				(Constructor<Compliance>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Compliance, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Compliance, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Compliance, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Compliance, Object>>();
		Map<String, BiConsumer<Compliance, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Compliance, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(Compliance compliance, Object uuidObject) {
					compliance.setUuid((String)uuidObject);
				}

			});
		attributeGetterFunctions.put(
			"complianceId",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getComplianceId();
				}

			});
		attributeSetterBiConsumers.put(
			"complianceId",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object complianceIdObject) {

					compliance.setComplianceId((Long)complianceIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object groupIdObject) {

					compliance.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object companyIdObject) {

					compliance.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"createdby",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getCreatedby();
				}

			});
		attributeSetterBiConsumers.put(
			"createdby",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object createdbyObject) {

					compliance.setCreatedby((Long)createdbyObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedby",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getModifiedby();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedby",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object modifiedbyObject) {

					compliance.setModifiedby((String)modifiedbyObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object createDateObject) {

					compliance.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object modifiedDateObject) {

					compliance.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"firstName",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getFirstName();
				}

			});
		attributeSetterBiConsumers.put(
			"firstName",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object firstNameObject) {

					compliance.setFirstName((String)firstNameObject);
				}

			});
		attributeGetterFunctions.put(
			"lastName",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getLastName();
				}

			});
		attributeSetterBiConsumers.put(
			"lastName",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object lastNameObject) {

					compliance.setLastName((String)lastNameObject);
				}

			});
		attributeGetterFunctions.put(
			"branchName",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getBranchName();
				}

			});
		attributeSetterBiConsumers.put(
			"branchName",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object branchNameObject) {

					compliance.setBranchName((String)branchNameObject);
				}

			});
		attributeGetterFunctions.put(
			"payrollNo",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getPayrollNo();
				}

			});
		attributeSetterBiConsumers.put(
			"payrollNo",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object payrollNoObject) {

					compliance.setPayrollNo((String)payrollNoObject);
				}

			});
		attributeGetterFunctions.put(
			"terminationReason",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getTerminationReason();
				}

			});
		attributeSetterBiConsumers.put(
			"terminationReason",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object terminationReasonObject) {

					compliance.setTerminationReason(
						(String)terminationReasonObject);
				}

			});
		attributeGetterFunctions.put(
			"terminationCode",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getTerminationCode();
				}

			});
		attributeSetterBiConsumers.put(
			"terminationCode",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object terminationCodeObject) {

					compliance.setTerminationCode(
						(String)terminationCodeObject);
				}

			});
		attributeGetterFunctions.put(
			"formerBranch",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getFormerBranch();
				}

			});
		attributeSetterBiConsumers.put(
			"formerBranch",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object formerBranchObject) {

					compliance.setFormerBranch((String)formerBranchObject);
				}

			});
		attributeGetterFunctions.put(
			"contractId",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getContractId();
				}

			});
		attributeSetterBiConsumers.put(
			"contractId",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object contractIdObject) {

					compliance.setContractId((String)contractIdObject);
				}

			});
		attributeGetterFunctions.put(
			"entityId",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getEntityId();
				}

			});
		attributeSetterBiConsumers.put(
			"entityId",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object entityIdObject) {

					compliance.setEntityId((String)entityIdObject);
				}

			});
		attributeGetterFunctions.put(
			"approvalDate",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getApprovalDate();
				}

			});
		attributeSetterBiConsumers.put(
			"approvalDate",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object approvalDateObject) {

					compliance.setApprovalDate((String)approvalDateObject);
				}

			});
		attributeGetterFunctions.put(
			"comments",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getComments();
				}

			});
		attributeSetterBiConsumers.put(
			"comments",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object commentsObject) {

					compliance.setComments((String)commentsObject);
				}

			});
		attributeGetterFunctions.put(
			"approverContractNumber",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getApproverContractNumber();
				}

			});
		attributeSetterBiConsumers.put(
			"approverContractNumber",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance,
					Object approverContractNumberObject) {

					compliance.setApproverContractNumber(
						(String)approverContractNumberObject);
				}

			});
		attributeGetterFunctions.put(
			"agentVerdict",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getAgentVerdict();
				}

			});
		attributeSetterBiConsumers.put(
			"agentVerdict",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object agentVerdictObject) {

					compliance.setAgentVerdict((String)agentVerdictObject);
				}

			});
		attributeGetterFunctions.put(
			"agentAction",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getAgentAction();
				}

			});
		attributeSetterBiConsumers.put(
			"agentAction",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object agentActionObject) {

					compliance.setAgentAction((String)agentActionObject);
				}

			});
		attributeGetterFunctions.put(
			"processedFlag",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getProcessedFlag();
				}

			});
		attributeSetterBiConsumers.put(
			"processedFlag",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object processedFlagObject) {

					compliance.setProcessedFlag((String)processedFlagObject);
				}

			});
		attributeGetterFunctions.put(
			"errorReason",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getErrorReason();
				}

			});
		attributeSetterBiConsumers.put(
			"errorReason",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object errorReasonObject) {

					compliance.setErrorReason((String)errorReasonObject);
				}

			});
		attributeGetterFunctions.put(
			"assignmentStatus",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getAssignmentStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"assignmentStatus",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object assignmentStatusObject) {

					compliance.setAssignmentStatus(
						(String)assignmentStatusObject);
				}

			});
		attributeGetterFunctions.put(
			"capacity",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getCapacity();
				}

			});
		attributeSetterBiConsumers.put(
			"capacity",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object capacityObject) {

					compliance.setCapacity((String)capacityObject);
				}

			});
		attributeGetterFunctions.put(
			"positionId",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getPositionId();
				}

			});
		attributeSetterBiConsumers.put(
			"positionId",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object positionIdObject) {

					compliance.setPositionId((String)positionIdObject);
				}

			});
		attributeGetterFunctions.put(
			"orgId",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getOrgId();
				}

			});
		attributeSetterBiConsumers.put(
			"orgId",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(Compliance compliance, Object orgIdObject) {
					compliance.setOrgId((String)orgIdObject);
				}

			});
		attributeGetterFunctions.put(
			"historyStartDate",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getHistoryStartDate();
				}

			});
		attributeSetterBiConsumers.put(
			"historyStartDate",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object historyStartDateObject) {

					compliance.setHistoryStartDate(
						(String)historyStartDateObject);
				}

			});
		attributeGetterFunctions.put(
			"oldOrgId",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getOldOrgId();
				}

			});
		attributeSetterBiConsumers.put(
			"oldOrgId",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object oldOrgIdObject) {

					compliance.setOldOrgId((String)oldOrgIdObject);
				}

			});
		attributeGetterFunctions.put(
			"oldPositionId",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getOldPositionId();
				}

			});
		attributeSetterBiConsumers.put(
			"oldPositionId",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object oldPositionIdObject) {

					compliance.setOldPositionId((String)oldPositionIdObject);
				}

			});
		attributeGetterFunctions.put(
			"contractEffectiveEndDate",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getContractEffectiveEndDate();
				}

			});
		attributeSetterBiConsumers.put(
			"contractEffectiveEndDate",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance,
					Object contractEffectiveEndDateObject) {

					compliance.setContractEffectiveEndDate(
						(String)contractEffectiveEndDateObject);
				}

			});
		attributeGetterFunctions.put(
			"applicationTye",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getApplicationTye();
				}

			});
		attributeSetterBiConsumers.put(
			"applicationTye",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object applicationTyeObject) {

					compliance.setApplicationTye((String)applicationTyeObject);
				}

			});
		attributeGetterFunctions.put(
			"applicationCategory",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getApplicationCategory();
				}

			});
		attributeSetterBiConsumers.put(
			"applicationCategory",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object applicationCategoryObject) {

					compliance.setApplicationCategory(
						(String)applicationCategoryObject);
				}

			});
		attributeGetterFunctions.put(
			"firstapprover",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getFirstapprover();
				}

			});
		attributeSetterBiConsumers.put(
			"firstapprover",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object firstapproverObject) {

					compliance.setFirstapprover((String)firstapproverObject);
				}

			});
		attributeGetterFunctions.put(
			"secondapprover",
			new Function<Compliance, Object>() {

				@Override
				public Object apply(Compliance compliance) {
					return compliance.getSecondapprover();
				}

			});
		attributeSetterBiConsumers.put(
			"secondapprover",
			new BiConsumer<Compliance, Object>() {

				@Override
				public void accept(
					Compliance compliance, Object secondapproverObject) {

					compliance.setSecondapprover((String)secondapproverObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getComplianceId() {
		return _complianceId;
	}

	@Override
	public void setComplianceId(long complianceId) {
		_complianceId = complianceId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getCreatedby() {
		return _createdby;
	}

	@Override
	public void setCreatedby(long createdby) {
		_createdby = createdby;
	}

	@JSON
	@Override
	public String getModifiedby() {
		if (_modifiedby == null) {
			return "";
		}
		else {
			return _modifiedby;
		}
	}

	@Override
	public void setModifiedby(String modifiedby) {
		_modifiedby = modifiedby;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		_firstName = firstName;
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		_lastName = lastName;
	}

	@JSON
	@Override
	public String getBranchName() {
		if (_branchName == null) {
			return "";
		}
		else {
			return _branchName;
		}
	}

	@Override
	public void setBranchName(String branchName) {
		_branchName = branchName;
	}

	@JSON
	@Override
	public String getPayrollNo() {
		if (_payrollNo == null) {
			return "";
		}
		else {
			return _payrollNo;
		}
	}

	@Override
	public void setPayrollNo(String payrollNo) {
		_payrollNo = payrollNo;
	}

	@JSON
	@Override
	public String getTerminationReason() {
		if (_terminationReason == null) {
			return "";
		}
		else {
			return _terminationReason;
		}
	}

	@Override
	public void setTerminationReason(String terminationReason) {
		_terminationReason = terminationReason;
	}

	@JSON
	@Override
	public String getTerminationCode() {
		if (_terminationCode == null) {
			return "";
		}
		else {
			return _terminationCode;
		}
	}

	@Override
	public void setTerminationCode(String terminationCode) {
		_terminationCode = terminationCode;
	}

	@JSON
	@Override
	public String getFormerBranch() {
		if (_formerBranch == null) {
			return "";
		}
		else {
			return _formerBranch;
		}
	}

	@Override
	public void setFormerBranch(String formerBranch) {
		_formerBranch = formerBranch;
	}

	@JSON
	@Override
	public String getContractId() {
		if (_contractId == null) {
			return "";
		}
		else {
			return _contractId;
		}
	}

	@Override
	public void setContractId(String contractId) {
		_contractId = contractId;
	}

	@JSON
	@Override
	public String getEntityId() {
		if (_entityId == null) {
			return "";
		}
		else {
			return _entityId;
		}
	}

	@Override
	public void setEntityId(String entityId) {
		_entityId = entityId;
	}

	@JSON
	@Override
	public String getApprovalDate() {
		if (_approvalDate == null) {
			return "";
		}
		else {
			return _approvalDate;
		}
	}

	@Override
	public void setApprovalDate(String approvalDate) {
		_approvalDate = approvalDate;
	}

	@JSON
	@Override
	public String getComments() {
		if (_comments == null) {
			return "";
		}
		else {
			return _comments;
		}
	}

	@Override
	public void setComments(String comments) {
		_comments = comments;
	}

	@JSON
	@Override
	public String getApproverContractNumber() {
		if (_approverContractNumber == null) {
			return "";
		}
		else {
			return _approverContractNumber;
		}
	}

	@Override
	public void setApproverContractNumber(String approverContractNumber) {
		_approverContractNumber = approverContractNumber;
	}

	@JSON
	@Override
	public String getAgentVerdict() {
		if (_agentVerdict == null) {
			return "";
		}
		else {
			return _agentVerdict;
		}
	}

	@Override
	public void setAgentVerdict(String agentVerdict) {
		_agentVerdict = agentVerdict;
	}

	@JSON
	@Override
	public String getAgentAction() {
		if (_agentAction == null) {
			return "";
		}
		else {
			return _agentAction;
		}
	}

	@Override
	public void setAgentAction(String agentAction) {
		_agentAction = agentAction;
	}

	@JSON
	@Override
	public String getProcessedFlag() {
		if (_processedFlag == null) {
			return "";
		}
		else {
			return _processedFlag;
		}
	}

	@Override
	public void setProcessedFlag(String processedFlag) {
		_processedFlag = processedFlag;
	}

	@JSON
	@Override
	public String getErrorReason() {
		if (_errorReason == null) {
			return "";
		}
		else {
			return _errorReason;
		}
	}

	@Override
	public void setErrorReason(String errorReason) {
		_errorReason = errorReason;
	}

	@JSON
	@Override
	public String getAssignmentStatus() {
		if (_assignmentStatus == null) {
			return "";
		}
		else {
			return _assignmentStatus;
		}
	}

	@Override
	public void setAssignmentStatus(String assignmentStatus) {
		_assignmentStatus = assignmentStatus;
	}

	@JSON
	@Override
	public String getCapacity() {
		if (_capacity == null) {
			return "";
		}
		else {
			return _capacity;
		}
	}

	@Override
	public void setCapacity(String capacity) {
		_capacity = capacity;
	}

	@JSON
	@Override
	public String getPositionId() {
		if (_positionId == null) {
			return "";
		}
		else {
			return _positionId;
		}
	}

	@Override
	public void setPositionId(String positionId) {
		_positionId = positionId;
	}

	@JSON
	@Override
	public String getOrgId() {
		if (_orgId == null) {
			return "";
		}
		else {
			return _orgId;
		}
	}

	@Override
	public void setOrgId(String orgId) {
		_orgId = orgId;
	}

	@JSON
	@Override
	public String getHistoryStartDate() {
		if (_historyStartDate == null) {
			return "";
		}
		else {
			return _historyStartDate;
		}
	}

	@Override
	public void setHistoryStartDate(String historyStartDate) {
		_historyStartDate = historyStartDate;
	}

	@JSON
	@Override
	public String getOldOrgId() {
		if (_oldOrgId == null) {
			return "";
		}
		else {
			return _oldOrgId;
		}
	}

	@Override
	public void setOldOrgId(String oldOrgId) {
		_oldOrgId = oldOrgId;
	}

	@JSON
	@Override
	public String getOldPositionId() {
		if (_oldPositionId == null) {
			return "";
		}
		else {
			return _oldPositionId;
		}
	}

	@Override
	public void setOldPositionId(String oldPositionId) {
		_oldPositionId = oldPositionId;
	}

	@JSON
	@Override
	public String getContractEffectiveEndDate() {
		if (_contractEffectiveEndDate == null) {
			return "";
		}
		else {
			return _contractEffectiveEndDate;
		}
	}

	@Override
	public void setContractEffectiveEndDate(String contractEffectiveEndDate) {
		_contractEffectiveEndDate = contractEffectiveEndDate;
	}

	@JSON
	@Override
	public String getApplicationTye() {
		if (_applicationTye == null) {
			return "";
		}
		else {
			return _applicationTye;
		}
	}

	@Override
	public void setApplicationTye(String applicationTye) {
		_applicationTye = applicationTye;
	}

	@JSON
	@Override
	public String getApplicationCategory() {
		if (_applicationCategory == null) {
			return "";
		}
		else {
			return _applicationCategory;
		}
	}

	@Override
	public void setApplicationCategory(String applicationCategory) {
		_applicationCategory = applicationCategory;
	}

	@JSON
	@Override
	public String getFirstapprover() {
		if (_firstapprover == null) {
			return "";
		}
		else {
			return _firstapprover;
		}
	}

	@Override
	public void setFirstapprover(String firstapprover) {
		_firstapprover = firstapprover;
	}

	@JSON
	@Override
	public String getSecondapprover() {
		if (_secondapprover == null) {
			return "";
		}
		else {
			return _secondapprover;
		}
	}

	@Override
	public void setSecondapprover(String secondapprover) {
		_secondapprover = secondapprover;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Compliance.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Compliance.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Compliance toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Compliance>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ComplianceImpl complianceImpl = new ComplianceImpl();

		complianceImpl.setUuid(getUuid());
		complianceImpl.setComplianceId(getComplianceId());
		complianceImpl.setGroupId(getGroupId());
		complianceImpl.setCompanyId(getCompanyId());
		complianceImpl.setCreatedby(getCreatedby());
		complianceImpl.setModifiedby(getModifiedby());
		complianceImpl.setCreateDate(getCreateDate());
		complianceImpl.setModifiedDate(getModifiedDate());
		complianceImpl.setFirstName(getFirstName());
		complianceImpl.setLastName(getLastName());
		complianceImpl.setBranchName(getBranchName());
		complianceImpl.setPayrollNo(getPayrollNo());
		complianceImpl.setTerminationReason(getTerminationReason());
		complianceImpl.setTerminationCode(getTerminationCode());
		complianceImpl.setFormerBranch(getFormerBranch());
		complianceImpl.setContractId(getContractId());
		complianceImpl.setEntityId(getEntityId());
		complianceImpl.setApprovalDate(getApprovalDate());
		complianceImpl.setComments(getComments());
		complianceImpl.setApproverContractNumber(getApproverContractNumber());
		complianceImpl.setAgentVerdict(getAgentVerdict());
		complianceImpl.setAgentAction(getAgentAction());
		complianceImpl.setProcessedFlag(getProcessedFlag());
		complianceImpl.setErrorReason(getErrorReason());
		complianceImpl.setAssignmentStatus(getAssignmentStatus());
		complianceImpl.setCapacity(getCapacity());
		complianceImpl.setPositionId(getPositionId());
		complianceImpl.setOrgId(getOrgId());
		complianceImpl.setHistoryStartDate(getHistoryStartDate());
		complianceImpl.setOldOrgId(getOldOrgId());
		complianceImpl.setOldPositionId(getOldPositionId());
		complianceImpl.setContractEffectiveEndDate(
			getContractEffectiveEndDate());
		complianceImpl.setApplicationTye(getApplicationTye());
		complianceImpl.setApplicationCategory(getApplicationCategory());
		complianceImpl.setFirstapprover(getFirstapprover());
		complianceImpl.setSecondapprover(getSecondapprover());

		complianceImpl.resetOriginalValues();

		return complianceImpl;
	}

	@Override
	public int compareTo(Compliance compliance) {
		long primaryKey = compliance.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Compliance)) {
			return false;
		}

		Compliance compliance = (Compliance)obj;

		long primaryKey = compliance.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ComplianceModelImpl complianceModelImpl = this;

		complianceModelImpl._originalUuid = complianceModelImpl._uuid;

		complianceModelImpl._originalGroupId = complianceModelImpl._groupId;

		complianceModelImpl._setOriginalGroupId = false;

		complianceModelImpl._originalCompanyId = complianceModelImpl._companyId;

		complianceModelImpl._setOriginalCompanyId = false;

		complianceModelImpl._setModifiedDate = false;

		complianceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Compliance> toCacheModel() {
		ComplianceCacheModel complianceCacheModel = new ComplianceCacheModel();

		complianceCacheModel.uuid = getUuid();

		String uuid = complianceCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			complianceCacheModel.uuid = null;
		}

		complianceCacheModel.complianceId = getComplianceId();

		complianceCacheModel.groupId = getGroupId();

		complianceCacheModel.companyId = getCompanyId();

		complianceCacheModel.createdby = getCreatedby();

		complianceCacheModel.modifiedby = getModifiedby();

		String modifiedby = complianceCacheModel.modifiedby;

		if ((modifiedby != null) && (modifiedby.length() == 0)) {
			complianceCacheModel.modifiedby = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			complianceCacheModel.createDate = createDate.getTime();
		}
		else {
			complianceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			complianceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			complianceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		complianceCacheModel.firstName = getFirstName();

		String firstName = complianceCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			complianceCacheModel.firstName = null;
		}

		complianceCacheModel.lastName = getLastName();

		String lastName = complianceCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			complianceCacheModel.lastName = null;
		}

		complianceCacheModel.branchName = getBranchName();

		String branchName = complianceCacheModel.branchName;

		if ((branchName != null) && (branchName.length() == 0)) {
			complianceCacheModel.branchName = null;
		}

		complianceCacheModel.payrollNo = getPayrollNo();

		String payrollNo = complianceCacheModel.payrollNo;

		if ((payrollNo != null) && (payrollNo.length() == 0)) {
			complianceCacheModel.payrollNo = null;
		}

		complianceCacheModel.terminationReason = getTerminationReason();

		String terminationReason = complianceCacheModel.terminationReason;

		if ((terminationReason != null) && (terminationReason.length() == 0)) {
			complianceCacheModel.terminationReason = null;
		}

		complianceCacheModel.terminationCode = getTerminationCode();

		String terminationCode = complianceCacheModel.terminationCode;

		if ((terminationCode != null) && (terminationCode.length() == 0)) {
			complianceCacheModel.terminationCode = null;
		}

		complianceCacheModel.formerBranch = getFormerBranch();

		String formerBranch = complianceCacheModel.formerBranch;

		if ((formerBranch != null) && (formerBranch.length() == 0)) {
			complianceCacheModel.formerBranch = null;
		}

		complianceCacheModel.contractId = getContractId();

		String contractId = complianceCacheModel.contractId;

		if ((contractId != null) && (contractId.length() == 0)) {
			complianceCacheModel.contractId = null;
		}

		complianceCacheModel.entityId = getEntityId();

		String entityId = complianceCacheModel.entityId;

		if ((entityId != null) && (entityId.length() == 0)) {
			complianceCacheModel.entityId = null;
		}

		complianceCacheModel.approvalDate = getApprovalDate();

		String approvalDate = complianceCacheModel.approvalDate;

		if ((approvalDate != null) && (approvalDate.length() == 0)) {
			complianceCacheModel.approvalDate = null;
		}

		complianceCacheModel.comments = getComments();

		String comments = complianceCacheModel.comments;

		if ((comments != null) && (comments.length() == 0)) {
			complianceCacheModel.comments = null;
		}

		complianceCacheModel.approverContractNumber =
			getApproverContractNumber();

		String approverContractNumber =
			complianceCacheModel.approverContractNumber;

		if ((approverContractNumber != null) &&
			(approverContractNumber.length() == 0)) {

			complianceCacheModel.approverContractNumber = null;
		}

		complianceCacheModel.agentVerdict = getAgentVerdict();

		String agentVerdict = complianceCacheModel.agentVerdict;

		if ((agentVerdict != null) && (agentVerdict.length() == 0)) {
			complianceCacheModel.agentVerdict = null;
		}

		complianceCacheModel.agentAction = getAgentAction();

		String agentAction = complianceCacheModel.agentAction;

		if ((agentAction != null) && (agentAction.length() == 0)) {
			complianceCacheModel.agentAction = null;
		}

		complianceCacheModel.processedFlag = getProcessedFlag();

		String processedFlag = complianceCacheModel.processedFlag;

		if ((processedFlag != null) && (processedFlag.length() == 0)) {
			complianceCacheModel.processedFlag = null;
		}

		complianceCacheModel.errorReason = getErrorReason();

		String errorReason = complianceCacheModel.errorReason;

		if ((errorReason != null) && (errorReason.length() == 0)) {
			complianceCacheModel.errorReason = null;
		}

		complianceCacheModel.assignmentStatus = getAssignmentStatus();

		String assignmentStatus = complianceCacheModel.assignmentStatus;

		if ((assignmentStatus != null) && (assignmentStatus.length() == 0)) {
			complianceCacheModel.assignmentStatus = null;
		}

		complianceCacheModel.capacity = getCapacity();

		String capacity = complianceCacheModel.capacity;

		if ((capacity != null) && (capacity.length() == 0)) {
			complianceCacheModel.capacity = null;
		}

		complianceCacheModel.positionId = getPositionId();

		String positionId = complianceCacheModel.positionId;

		if ((positionId != null) && (positionId.length() == 0)) {
			complianceCacheModel.positionId = null;
		}

		complianceCacheModel.orgId = getOrgId();

		String orgId = complianceCacheModel.orgId;

		if ((orgId != null) && (orgId.length() == 0)) {
			complianceCacheModel.orgId = null;
		}

		complianceCacheModel.historyStartDate = getHistoryStartDate();

		String historyStartDate = complianceCacheModel.historyStartDate;

		if ((historyStartDate != null) && (historyStartDate.length() == 0)) {
			complianceCacheModel.historyStartDate = null;
		}

		complianceCacheModel.oldOrgId = getOldOrgId();

		String oldOrgId = complianceCacheModel.oldOrgId;

		if ((oldOrgId != null) && (oldOrgId.length() == 0)) {
			complianceCacheModel.oldOrgId = null;
		}

		complianceCacheModel.oldPositionId = getOldPositionId();

		String oldPositionId = complianceCacheModel.oldPositionId;

		if ((oldPositionId != null) && (oldPositionId.length() == 0)) {
			complianceCacheModel.oldPositionId = null;
		}

		complianceCacheModel.contractEffectiveEndDate =
			getContractEffectiveEndDate();

		String contractEffectiveEndDate =
			complianceCacheModel.contractEffectiveEndDate;

		if ((contractEffectiveEndDate != null) &&
			(contractEffectiveEndDate.length() == 0)) {

			complianceCacheModel.contractEffectiveEndDate = null;
		}

		complianceCacheModel.applicationTye = getApplicationTye();

		String applicationTye = complianceCacheModel.applicationTye;

		if ((applicationTye != null) && (applicationTye.length() == 0)) {
			complianceCacheModel.applicationTye = null;
		}

		complianceCacheModel.applicationCategory = getApplicationCategory();

		String applicationCategory = complianceCacheModel.applicationCategory;

		if ((applicationCategory != null) &&
			(applicationCategory.length() == 0)) {

			complianceCacheModel.applicationCategory = null;
		}

		complianceCacheModel.firstapprover = getFirstapprover();

		String firstapprover = complianceCacheModel.firstapprover;

		if ((firstapprover != null) && (firstapprover.length() == 0)) {
			complianceCacheModel.firstapprover = null;
		}

		complianceCacheModel.secondapprover = getSecondapprover();

		String secondapprover = complianceCacheModel.secondapprover;

		if ((secondapprover != null) && (secondapprover.length() == 0)) {
			complianceCacheModel.secondapprover = null;
		}

		return complianceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Compliance, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Compliance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Compliance, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Compliance)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Compliance, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Compliance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Compliance, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Compliance)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Compliance>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _complianceId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _createdby;
	private String _modifiedby;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _firstName;
	private String _lastName;
	private String _branchName;
	private String _payrollNo;
	private String _terminationReason;
	private String _terminationCode;
	private String _formerBranch;
	private String _contractId;
	private String _entityId;
	private String _approvalDate;
	private String _comments;
	private String _approverContractNumber;
	private String _agentVerdict;
	private String _agentAction;
	private String _processedFlag;
	private String _errorReason;
	private String _assignmentStatus;
	private String _capacity;
	private String _positionId;
	private String _orgId;
	private String _historyStartDate;
	private String _oldOrgId;
	private String _oldPositionId;
	private String _contractEffectiveEndDate;
	private String _applicationTye;
	private String _applicationCategory;
	private String _firstapprover;
	private String _secondapprover;
	private long _columnBitmask;
	private Compliance _escapedModel;

}