/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tamarix.compliance.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Matrix service. Represents a row in the &quot;Compliance_Matrix&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tamarix.compliance.model.impl.MatrixModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tamarix.compliance.model.impl.MatrixImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Matrix
 * @generated
 */
@ProviderType
public interface MatrixModel
	extends BaseModel<Matrix>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a matrix model instance should use the {@link Matrix} interface instead.
	 */

	/**
	 * Returns the primary key of this matrix.
	 *
	 * @return the primary key of this matrix
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this matrix.
	 *
	 * @param primaryKey the primary key of this matrix
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this matrix.
	 *
	 * @return the uuid of this matrix
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this matrix.
	 *
	 * @param uuid the uuid of this matrix
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the application ID of this matrix.
	 *
	 * @return the application ID of this matrix
	 */
	public long getApplicationId();

	/**
	 * Sets the application ID of this matrix.
	 *
	 * @param applicationId the application ID of this matrix
	 */
	public void setApplicationId(long applicationId);

	/**
	 * Returns the group ID of this matrix.
	 *
	 * @return the group ID of this matrix
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this matrix.
	 *
	 * @param groupId the group ID of this matrix
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this matrix.
	 *
	 * @return the company ID of this matrix
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this matrix.
	 *
	 * @param companyId the company ID of this matrix
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the createdby of this matrix.
	 *
	 * @return the createdby of this matrix
	 */
	public long getCreatedby();

	/**
	 * Sets the createdby of this matrix.
	 *
	 * @param createdby the createdby of this matrix
	 */
	public void setCreatedby(long createdby);

	/**
	 * Returns the modifiedby of this matrix.
	 *
	 * @return the modifiedby of this matrix
	 */
	@AutoEscape
	public String getModifiedby();

	/**
	 * Sets the modifiedby of this matrix.
	 *
	 * @param modifiedby the modifiedby of this matrix
	 */
	public void setModifiedby(String modifiedby);

	/**
	 * Returns the create date of this matrix.
	 *
	 * @return the create date of this matrix
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this matrix.
	 *
	 * @param createDate the create date of this matrix
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this matrix.
	 *
	 * @return the modified date of this matrix
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this matrix.
	 *
	 * @param modifiedDate the modified date of this matrix
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the application type of this matrix.
	 *
	 * @return the application type of this matrix
	 */
	@AutoEscape
	public String getApplicationType();

	/**
	 * Sets the application type of this matrix.
	 *
	 * @param applicationType the application type of this matrix
	 */
	public void setApplicationType(String applicationType);

	/**
	 * Returns the application category of this matrix.
	 *
	 * @return the application category of this matrix
	 */
	@AutoEscape
	public String getApplicationCategory();

	/**
	 * Sets the application category of this matrix.
	 *
	 * @param applicationCategory the application category of this matrix
	 */
	public void setApplicationCategory(String applicationCategory);

	/**
	 * Returns the responsible actor of this matrix.
	 *
	 * @return the responsible actor of this matrix
	 */
	@AutoEscape
	public String getResponsibleActor();

	/**
	 * Sets the responsible actor of this matrix.
	 *
	 * @param responsibleActor the responsible actor of this matrix
	 */
	public void setResponsibleActor(String responsibleActor);

	/**
	 * Returns the responsible actor2 of this matrix.
	 *
	 * @return the responsible actor2 of this matrix
	 */
	@AutoEscape
	public String getResponsibleActor2();

	/**
	 * Sets the responsible actor2 of this matrix.
	 *
	 * @param responsibleActor2 the responsible actor2 of this matrix
	 */
	public void setResponsibleActor2(String responsibleActor2);

	/**
	 * Returns the backup actor of this matrix.
	 *
	 * @return the backup actor of this matrix
	 */
	@AutoEscape
	public String getBackupActor();

	/**
	 * Sets the backup actor of this matrix.
	 *
	 * @param backupActor the backup actor of this matrix
	 */
	public void setBackupActor(String backupActor);

	/**
	 * Returns the backup actor2 of this matrix.
	 *
	 * @return the backup actor2 of this matrix
	 */
	@AutoEscape
	public String getBackupActor2();

	/**
	 * Sets the backup actor2 of this matrix.
	 *
	 * @param backupActor2 the backup actor2 of this matrix
	 */
	public void setBackupActor2(String backupActor2);

	/**
	 * Returns the approver of this matrix.
	 *
	 * @return the approver of this matrix
	 */
	@AutoEscape
	public String getApprover();

	/**
	 * Sets the approver of this matrix.
	 *
	 * @param approver the approver of this matrix
	 */
	public void setApprover(String approver);

	/**
	 * Returns the approver2 of this matrix.
	 *
	 * @return the approver2 of this matrix
	 */
	@AutoEscape
	public String getApprover2();

	/**
	 * Sets the approver2 of this matrix.
	 *
	 * @param approver2 the approver2 of this matrix
	 */
	public void setApprover2(String approver2);

	/**
	 * Returns the backup approver of this matrix.
	 *
	 * @return the backup approver of this matrix
	 */
	@AutoEscape
	public String getBackupApprover();

	/**
	 * Sets the backup approver of this matrix.
	 *
	 * @param backupApprover the backup approver of this matrix
	 */
	public void setBackupApprover(String backupApprover);

	/**
	 * Returns the backup approver2 of this matrix.
	 *
	 * @return the backup approver2 of this matrix
	 */
	@AutoEscape
	public String getBackupApprover2();

	/**
	 * Sets the backup approver2 of this matrix.
	 *
	 * @param backupApprover2 the backup approver2 of this matrix
	 */
	public void setBackupApprover2(String backupApprover2);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Matrix matrix);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Matrix> toCacheModel();

	@Override
	public Matrix toEscapedModel();

	@Override
	public Matrix toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}