/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tamarix.compliance.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.tamarix.compliance.model.Compliance;
import com.tamarix.compliance.service.ComplianceService;
import com.tamarix.compliance.service.persistence.ComplianceFinder;
import com.tamarix.compliance.service.persistence.CompliancePersistence;
import com.tamarix.compliance.service.persistence.MatrixPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the compliance remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.tamarix.compliance.service.impl.ComplianceServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.tamarix.compliance.service.impl.ComplianceServiceImpl
 * @generated
 */
public abstract class ComplianceServiceBaseImpl
	extends BaseServiceImpl
	implements ComplianceService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ComplianceService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.tamarix.compliance.service.ComplianceServiceUtil</code>.
	 */

	/**
	 * Returns the compliance local service.
	 *
	 * @return the compliance local service
	 */
	public com.tamarix.compliance.service.ComplianceLocalService
		getComplianceLocalService() {

		return complianceLocalService;
	}

	/**
	 * Sets the compliance local service.
	 *
	 * @param complianceLocalService the compliance local service
	 */
	public void setComplianceLocalService(
		com.tamarix.compliance.service.ComplianceLocalService
			complianceLocalService) {

		this.complianceLocalService = complianceLocalService;
	}

	/**
	 * Returns the compliance remote service.
	 *
	 * @return the compliance remote service
	 */
	public ComplianceService getComplianceService() {
		return complianceService;
	}

	/**
	 * Sets the compliance remote service.
	 *
	 * @param complianceService the compliance remote service
	 */
	public void setComplianceService(ComplianceService complianceService) {
		this.complianceService = complianceService;
	}

	/**
	 * Returns the compliance persistence.
	 *
	 * @return the compliance persistence
	 */
	public CompliancePersistence getCompliancePersistence() {
		return compliancePersistence;
	}

	/**
	 * Sets the compliance persistence.
	 *
	 * @param compliancePersistence the compliance persistence
	 */
	public void setCompliancePersistence(
		CompliancePersistence compliancePersistence) {

		this.compliancePersistence = compliancePersistence;
	}

	/**
	 * Returns the compliance finder.
	 *
	 * @return the compliance finder
	 */
	public ComplianceFinder getComplianceFinder() {
		return complianceFinder;
	}

	/**
	 * Sets the compliance finder.
	 *
	 * @param complianceFinder the compliance finder
	 */
	public void setComplianceFinder(ComplianceFinder complianceFinder) {
		this.complianceFinder = complianceFinder;
	}

	/**
	 * Returns the matrix local service.
	 *
	 * @return the matrix local service
	 */
	public com.tamarix.compliance.service.MatrixLocalService
		getMatrixLocalService() {

		return matrixLocalService;
	}

	/**
	 * Sets the matrix local service.
	 *
	 * @param matrixLocalService the matrix local service
	 */
	public void setMatrixLocalService(
		com.tamarix.compliance.service.MatrixLocalService matrixLocalService) {

		this.matrixLocalService = matrixLocalService;
	}

	/**
	 * Returns the matrix remote service.
	 *
	 * @return the matrix remote service
	 */
	public com.tamarix.compliance.service.MatrixService getMatrixService() {
		return matrixService;
	}

	/**
	 * Sets the matrix remote service.
	 *
	 * @param matrixService the matrix remote service
	 */
	public void setMatrixService(
		com.tamarix.compliance.service.MatrixService matrixService) {

		this.matrixService = matrixService;
	}

	/**
	 * Returns the matrix persistence.
	 *
	 * @return the matrix persistence
	 */
	public MatrixPersistence getMatrixPersistence() {
		return matrixPersistence;
	}

	/**
	 * Sets the matrix persistence.
	 *
	 * @param matrixPersistence the matrix persistence
	 */
	public void setMatrixPersistence(MatrixPersistence matrixPersistence) {
		this.matrixPersistence = matrixPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService
		getClassNameService() {

		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {

		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {

		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ComplianceService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Compliance.class;
	}

	protected String getModelClassName() {
		return Compliance.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = compliancePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.tamarix.compliance.service.ComplianceLocalService.class
	)
	protected com.tamarix.compliance.service.ComplianceLocalService
		complianceLocalService;

	@BeanReference(type = ComplianceService.class)
	protected ComplianceService complianceService;

	@BeanReference(type = CompliancePersistence.class)
	protected CompliancePersistence compliancePersistence;

	@BeanReference(type = ComplianceFinder.class)
	protected ComplianceFinder complianceFinder;

	@BeanReference(
		type = com.tamarix.compliance.service.MatrixLocalService.class
	)
	protected com.tamarix.compliance.service.MatrixLocalService
		matrixLocalService;

	@BeanReference(type = com.tamarix.compliance.service.MatrixService.class)
	protected com.tamarix.compliance.service.MatrixService matrixService;

	@BeanReference(type = MatrixPersistence.class)
	protected MatrixPersistence matrixPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserService.class
	)
	protected com.liferay.portal.kernel.service.UserService userService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

}